name: ipcc-ar6-wg1-atlas-rees
channels:
  - santandermetgroup
  - conda-forge
  - r
  - defaults
dependencies:
  #- climate4r=1.5.1 dependencies
  # R minimum version
  - r-base >=3.6.3
  - r-climate4R.UDG #=      "v0.2.3"
  - r-loadeR.java #=        "v1.1.1"
  - r-loadeR #=             "v1.7.1"
  - r-loadeR.ECOMS #=       "v1.4.6"
  - r-transformeR #=        "v2.1.2"
  - r-downscaleR #=         "v3.3.3"
  - r-downscaleR.keras #=   "v1.0.0"
  - r-visualizeR #=         "v1.6.1"
  - r-convertR #=           "v0.2.0"
  - r-geoprocessoR #=       "v0.2.0"
  - r-climate4R.climdex #=  "v0.2.2"
  - r-climate4R.indices #=  "v0.2.0"
  - r-loadeR.2nc #=         "v0.1.2"
  - r-fireDanger #=         "v1.1.0"
  - r-VALUE #=              "v2.2.1"
  - r-climate4R.value #=    "v0.0.2"
  - r-mopa #=               "v1.0.2"
  - r-drought4R #=          "v0.2.0"
  - r-climate4R.datasets #= "v0.0.1"
  # Jupyter and JupyterHub dependencies
  - r-irkernel
  - jupyter
  - jupyterhub
  - notebook
  - jupyterlab
  - jupyter_nbextensions_configurator
  - nbgitpuller # required for decouple binder and repo
  # Dependencies for notebooks
  - r-devtools
  - r-gridextra
  - r-xtable
  - r-magrittr
  - r-httr
  - r-lattice
  - r-latticeExtra
  # Python dependencies from some notebooks
  - python =3.7
  - xarray
  - regionmask