name: ipcc-ar6-wg1-rees
channels:
  - conda-forge
  - r
  - defaults
  - santandermetgroup
  - conda-forge/label/broken
dependencies:
  #- r-climate4r ==2.5.3
  - r-base >=3.6.3,<3.7
  - r-climate4r.udg ==0.2.3
  - r-loader.java ==1.1.1
  - r-loader ==1.7.1
  - r-loader.ecoms ==1.4.6
  - r-transformer ==2.1.3
  - r-downscaler ==3.3.3
  - r-downscaler.keras ==1.0.0
  - r-visualizer ==1.6.1
  - r-convertr ==0.2.0
  - r-geoprocessor ==0.2.0
  - r-climate4r.climdex ==0.2.2
  - r-climate4r.indices ==0.2.0
  - r-loader.2nc ==0.1.2
  - r-firedanger ==1.1.0
  - r-value ==2.2.1
  - r-climate4r.value ==0.0.2
  - r-mopa ==1.0.0
  - r-drought4r ==0.2.0
  - r-climate4r.datasets ==0.0.1
  #python dependencies
  - python >=3.7,<3.8
  - iris ==3.0.4
  # Jupyter and JupyterHub dependencies
  - r-irkernel ==1.2
  - jupyter ==1.0.0 
  - jupyterhub ==1.4.2
  - notebook ==6.4.2
  - jupyterlab ==3.1.4
  - jupyter_nbextensions_configurator ==0.4.1
  - nbgitpuller ==0.10.1 # required for decouple binder and repo
  # Dependencies for notebooks
  - r-devtools ==2.4.1
  - r-gridextra ==2.3
  - r-xtable ==1.8_4
  - r-magrittr ==2.0.1
  - r-httr ==1.4.2
  - r-lattice ==0.20_44
  - r-latticeextra ==0.6_29
  # Python dependencies from some notebooks
  - xarray ==0.19.0
  - regionmask ==0.7.0